version: '3.1'
services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  integration:
    image: integration:0.0.1-SNAPSHOT
    ports:
      - '8080:8080'
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis